version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      # test react-typescript
      - run: cd react-typescript && yarn install --frozen-lockfile
      - run: yarn test
      # test rest-express-typescript
      - run: cd rest-express-typescript && yarn install --frozen-lockfile
      - run: yarn test
