version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:af0ffb60afc34736f30fd8ce6662175ca29009835308fb7786e27ecfce424f20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
