version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:339b91052ff2f433453a963138fceb39edad08ec6398f17aaa91c34b9cf775ba
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd react-graphql-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd graphql-server-typescript && yarn install --frozen-lockfile && yarn test
