version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:918b8c997fef02cf2909a52d8b1d97cabe95abf50138e9dfc3b688dbb3c11dc9
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
