version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
