version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:126c0e45cefb24c8c75650a0e7ca08b4f4be288e4c643608487e8abfb0578175
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd react-graphql-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd graphql-server-typescript && yarn install --frozen-lockfile && yarn test
