version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f5606808bd76606fb053258b8281ad87c48811f1c10b2222850c2a3234a36bcb
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
