version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:9eae91f5ccf92fde771ac92d45b56327709206d8ed026c82dc26ec8b2142c27d
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: cd react-typescript && yarn install --frozen-lockfile && yarn test
      - run: cd rest-express-typescript && yarn install --frozen-lockfile && yarn test
